name: build, test, publish

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: rm package-lock.json # fixes https://github.com/matsilva/backo/actions/runs/13700270046/job/38312045835#step:5:14
      - run: npm i
      - run: npm test
      - name: Publish
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          echo "todo: npm publish --provenance --access public"
